//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The FoxyEcommConfiguration Configuration Section.
    /// </summary>
    public partial class FoxyEcommConfiguration : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the FoxyEcommConfiguration Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string FoxyEcommConfigurationSectionName = "FoxyEcommConfiguration";
        
        /// <summary>
        /// Gets the FoxyEcommConfiguration instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public static global::FoxyEcomm.Common.Models.FoxyEcommConfiguration Instance
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.FoxyEcommConfiguration)(global::System.Configuration.ConfigurationManager.GetSection(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.FoxyEcommConfigurationSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region CommandQueue Property
        /// <summary>
        /// The XML name of the <see cref="CommandQueue"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string CommandQueuePropertyName = "commandQueue";
        
        /// <summary>
        /// Gets or sets the CommandQueue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The CommandQueue.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.CommandQueuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement CommandQueue
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.CommandQueuePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.CommandQueuePropertyName] = value;
            }
        }
        #endregion
        
        #region EventQueue Property
        /// <summary>
        /// The XML name of the <see cref="EventQueue"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string EventQueuePropertyName = "eventQueue";
        
        /// <summary>
        /// Gets or sets the EventQueue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The EventQueue.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.EventQueuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement EventQueue
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.EventQueuePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.EventQueuePropertyName] = value;
            }
        }
        #endregion
        
        #region Services Property
        /// <summary>
        /// The XML name of the <see cref="Services"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ServicesPropertyName = "services";
        
        /// <summary>
        /// Gets or sets the Services.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Services.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ServicesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.ServiceElementCollection Services
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.ServiceElementCollection)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ServicesPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ServicesPropertyName] = value;
            }
        }
        #endregion
        
        #region ApplicationSetting Property
        /// <summary>
        /// The XML name of the <see cref="ApplicationSetting"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ApplicationSettingPropertyName = "application";
        
        /// <summary>
        /// Gets or sets the ApplicationSetting.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ApplicationSetting.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ApplicationSettingPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.ApplicationSettingElement ApplicationSetting
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.ApplicationSettingElement)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ApplicationSettingPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.ApplicationSettingPropertyName] = value;
            }
        }
        #endregion
        
        #region MongoEventStore Property
        /// <summary>
        /// The XML name of the <see cref="MongoEventStore"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string MongoEventStorePropertyName = "mongoEventStore";
        
        /// <summary>
        /// Gets or sets the MongoEventStore.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The MongoEventStore.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.MongoEventStorePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.MongoEventStoreElement MongoEventStore
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.MongoEventStoreElement)(base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.MongoEventStorePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.FoxyEcommConfiguration.MongoEventStorePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The SettingElement Configuration Element.
    /// </summary>
    public partial class SettingElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Key Property
        /// <summary>
        /// The XML name of the <see cref="Key"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string KeyPropertyName = "key";
        
        /// <summary>
        /// Gets or sets the Key.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Key.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.SettingElement.KeyPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Key
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.SettingElement.KeyPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.SettingElement.KeyPropertyName] = value;
            }
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.SettingElement.ValuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Value
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.SettingElement.ValuePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.SettingElement.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// A collection of SettingElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::FoxyEcomm.Common.Models.SettingElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::FoxyEcomm.Common.Models.SettingElementCollection.SettingElementPropertyName)]
    public partial class SettingElementCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SettingElementPropertyName = "setting";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::FoxyEcomm.Common.Models.SettingElementCollection.SettingElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::FoxyEcomm.Common.Models.SettingElementCollection.SettingElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::FoxyEcomm.Common.Models.SettingElement)(element)).Key;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::FoxyEcomm.Common.Models.SettingElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::FoxyEcomm.Common.Models.SettingElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::FoxyEcomm.Common.Models.SettingElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.SettingElement this[int index]
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.SettingElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.SettingElement this[object key]
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.SettingElement)(base.BaseGet(key)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="setting">The <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::FoxyEcomm.Common.Models.SettingElement setting)
        {
            base.BaseAdd(setting);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="setting">The <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::FoxyEcomm.Common.Models.SettingElement setting)
        {
            base.BaseRemove(this.GetElementKey(setting));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.SettingElement GetItemAt(int index)
        {
            return ((global::FoxyEcomm.Common.Models.SettingElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> with the specified key.
        /// </summary>
        /// <param name="key">The key of the <see cref="global::FoxyEcomm.Common.Models.SettingElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.SettingElement GetItemByKey(string key)
        {
            return ((global::FoxyEcomm.Common.Models.SettingElement)(base.BaseGet(((object)(key)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// A collection of ServiceElement instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::FoxyEcomm.Common.Models.ServiceElement), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::FoxyEcomm.Common.Models.ServiceElementCollection.ServiceElementPropertyName)]
    public partial class ServiceElementCollection : global::System.Configuration.ConfigurationElementCollection, global::System.Collections.Generic.ICollection<global::FoxyEcomm.Common.Models.ServiceElement>
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ServiceElementPropertyName = "service";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override string ElementName
        {
            get
            {
                return global::FoxyEcomm.Common.Models.ServiceElementCollection.ServiceElementPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::FoxyEcomm.Common.Models.ServiceElementCollection.ServiceElementPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::FoxyEcomm.Common.Models.ServiceElement)(element)).Type;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::FoxyEcomm.Common.Models.ServiceElement();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.ServiceElement this[int index]
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.ServiceElement)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> with the specified key.
        /// </summary>
        /// <param name="type">The key of the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.ServiceElement this[object type]
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.ServiceElement)(base.BaseGet(type)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="service">The <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Add(global::FoxyEcomm.Common.Models.ServiceElement service)
        {
            base.BaseAdd(service);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="service">The <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Remove(global::FoxyEcomm.Common.Models.ServiceElement service)
        {
            base.BaseRemove(this.GetElementKey(service));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.ServiceElement GetItemAt(int index)
        {
            return ((global::FoxyEcomm.Common.Models.ServiceElement)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> with the specified key.
        /// </summary>
        /// <param name="type">The key of the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public global::FoxyEcomm.Common.Models.ServiceElement GetItemByKey(string type)
        {
            return ((global::FoxyEcomm.Common.Models.ServiceElement)(base.BaseGet(((object)(type)))));
        }
        #endregion
        
        #region ICollection
        /// <summary>
        /// Removes all items from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void Clear()
        {
            base.BaseClear();
        }
        
        /// <summary>
        /// Determines whether the <see cref="global::System.Configuration.ConfigurationElementCollection"/> contains a specific value.
        /// </summary>
        /// <param name="service">The object to locate in the <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/>.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public bool Contains(global::FoxyEcomm.Common.Models.ServiceElement service)
        {
            return (base.BaseIndexOf(service) >= 0);
        }
        
        /// <summary>
        /// Copies the elements of the <see cref="global::System.Configuration.ConfigurationElementCollection"/> to an <see cref="System.Array"/>, starting at a particular <see cref="System.Array"/> index.
        /// </summary>
        /// <param name="array">The one-dimensional <see cref="System.Array"/> that is the destination of the elements copied from <see cref="global::System.Configuration.ConfigurationElementCollection"/>. The <see cref="System.Array"/> must have zero-based indexing.</param>
        /// <param name="arrayIndex">The zero-based index in <paramref name="array"/> at which copying begins.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public void CopyTo(global::FoxyEcomm.Common.Models.ServiceElement[] array, int arrayIndex)
        {
            base.CopyTo(array, arrayIndex);
        }
        
        /// <summary>
        /// Gets a value indicating whether the <see cref="global::System.Configuration.ConfigurationElementCollection"/> is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        bool global::System.Collections.Generic.ICollection<global::FoxyEcomm.Common.Models.ServiceElement>.IsReadOnly
        {
            get
            {
                return this.IsReadOnly();
            }
        }
        
        /// <summary>
        /// Removes the first occurrence of a specific object from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="item">The <see cref="global::FoxyEcomm.Common.Models.ServiceElement"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        bool global::System.Collections.Generic.ICollection<global::FoxyEcomm.Common.Models.ServiceElement>.Remove(global::FoxyEcomm.Common.Models.ServiceElement item)
        {
            int idx = base.BaseIndexOf(item);
            if ((idx == -1))
            {
                return false;
            }
            base.BaseRemoveAt(idx);
            return true;
        }
        
        /// <summary>
        /// Returns an enumerator that iterates through the collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public new global::System.Collections.Generic.IEnumerator<global::FoxyEcomm.Common.Models.ServiceElement> GetEnumerator()
        {
            global::System.Collections.Generic.List<global::FoxyEcomm.Common.Models.ServiceElement> list = new global::System.Collections.Generic.List<global::FoxyEcomm.Common.Models.ServiceElement>(base.Count);
            global::System.Collections.IEnumerator iter = base.GetEnumerator();
            for (; iter.MoveNext(); )
            {
                list.Add(((global::FoxyEcomm.Common.Models.ServiceElement)(iter.Current)));
            }
            return list.GetEnumerator();
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The ServiceElement Configuration Element.
    /// </summary>
    public partial class ServiceElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ServiceElement.TypePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Type
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.ServiceElement.TypePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ServiceElement.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region InstanceId Property
        /// <summary>
        /// The XML name of the <see cref="InstanceId"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string InstanceIdPropertyName = "instanceId";
        
        /// <summary>
        /// Gets or sets the InstanceId.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The InstanceId.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ServiceElement.InstanceIdPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string InstanceId
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.ServiceElement.InstanceIdPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ServiceElement.InstanceIdPropertyName] = value;
            }
        }
        #endregion
        
        #region Settings Property
        /// <summary>
        /// The XML name of the <see cref="Settings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string SettingsPropertyName = "settings";
        
        /// <summary>
        /// Gets or sets the Settings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Settings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ServiceElement.SettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.SettingElementCollection Settings
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.SettingElementCollection)(base[global::FoxyEcomm.Common.Models.ServiceElement.SettingsPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ServiceElement.SettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region LocalCommandQueue Property
        /// <summary>
        /// The XML name of the <see cref="LocalCommandQueue"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LocalCommandQueuePropertyName = "localCommandQueue";
        
        /// <summary>
        /// Gets or sets the LocalCommandQueue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LocalCommandQueue.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ServiceElement.LocalCommandQueuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement LocalCommandQueue
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement)(base[global::FoxyEcomm.Common.Models.ServiceElement.LocalCommandQueuePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ServiceElement.LocalCommandQueuePropertyName] = value;
            }
        }
        #endregion
        
        #region LocalEventQueue Property
        /// <summary>
        /// The XML name of the <see cref="LocalEventQueue"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string LocalEventQueuePropertyName = "localEventQueue";
        
        /// <summary>
        /// Gets or sets the LocalEventQueue.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The LocalEventQueue.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ServiceElement.LocalEventQueuePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement LocalEventQueue
        {
            get
            {
                return ((global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement)(base[global::FoxyEcomm.Common.Models.ServiceElement.LocalEventQueuePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ServiceElement.LocalEventQueuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The ApplicationSettingElement Configuration Element.
    /// </summary>
    public partial class ApplicationSettingElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Url Property
        /// <summary>
        /// The XML name of the <see cref="Url"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string UrlPropertyName = "url";
        
        /// <summary>
        /// Gets or sets represents the base url of the FoxyEcomm service.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("Represents the base url of the FoxyEcomm service.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.ApplicationSettingElement.UrlPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Url
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.ApplicationSettingElement.UrlPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.ApplicationSettingElement.UrlPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The MessageQueueConfigurationElement Configuration Element.
    /// </summary>
    public partial class MessageQueueConfigurationElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ConnectionUri Property
        /// <summary>
        /// The XML name of the <see cref="ConnectionUri"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ConnectionUriPropertyName = "connectionUri";
        
        /// <summary>
        /// Gets or sets the ConnectionUri.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ConnectionUri.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ConnectionUriPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string ConnectionUri
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ConnectionUriPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ConnectionUriPropertyName] = value;
            }
        }
        #endregion
        
        #region ExchangeName Property
        /// <summary>
        /// The XML name of the <see cref="ExchangeName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ExchangeNamePropertyName = "exchangeName";
        
        /// <summary>
        /// Gets or sets gets or sets the name of the resource of the message queue. A resource can be either a queue, or an exchange to which queues can be bound.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("Gets or sets the name of the resource of the message queue. A resource can be eit" +
            "her a queue, or an exchange to which queues can be bound.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ExchangeNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ExchangeName
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ExchangeNamePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.ExchangeNamePropertyName] = value;
            }
        }
        #endregion
        
        #region QueueName Property
        /// <summary>
        /// The XML name of the <see cref="QueueName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string QueueNamePropertyName = "queueName";
        
        /// <summary>
        /// Gets or sets the QueueName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The QueueName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.QueueNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string QueueName
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.QueueNamePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MessageQueueConfigurationElement.QueueNamePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// The MongoEventStoreElement Configuration Element.
    /// </summary>
    public partial class MongoEventStoreElement : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region ConnectionString Property
        /// <summary>
        /// The XML name of the <see cref="ConnectionString"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string ConnectionStringPropertyName = "connectionString";
        
        /// <summary>
        /// Gets or sets the ConnectionString.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The ConnectionString.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MongoEventStoreElement.ConnectionStringPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string ConnectionString
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.ConnectionStringPropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.ConnectionStringPropertyName] = value;
            }
        }
        #endregion
        
        #region Database Property
        /// <summary>
        /// The XML name of the <see cref="Database"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string DatabasePropertyName = "database";
        
        /// <summary>
        /// Gets or sets the Database.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Database.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MongoEventStoreElement.DatabasePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Database
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.DatabasePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.DatabasePropertyName] = value;
            }
        }
        #endregion
        
        #region CollectionName Property
        /// <summary>
        /// The XML name of the <see cref="CollectionName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        internal const string CollectionNamePropertyName = "collectionName";
        
        /// <summary>
        /// Gets or sets the CollectionName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
        [global::System.ComponentModel.DescriptionAttribute("The CollectionName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::FoxyEcomm.Common.Models.MongoEventStoreElement.CollectionNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string CollectionName
        {
            get
            {
                return ((string)(base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.CollectionNamePropertyName]));
            }
            set
            {
                base[global::FoxyEcomm.Common.Models.MongoEventStoreElement.CollectionNamePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace FoxyEcomm.Common.Models
{
    
    
    /// <summary>
    /// MessageQueueResourceType.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.0")]
    public enum MessageQueueResourceType
    {
        
        /// <summary>
        /// MessageExchange.
        /// </summary>
        MessageExchange,
        
        /// <summary>
        /// MessageQueue.
        /// </summary>
        MessageQueue,
    }
}
